[package]
name = "skrillax-server"
version = "0.1.0"
edition = "2021"

[dependencies]
kanal = "0.1.1"
skrillax-stream.workspace = true
tokio-util = "0.7"
tokio = { workspace = true }
tracing = { workspace = true }
