server-id = 1
name = "Skrillax"
rpc-address = "localhost"
rpc-port = 1337
region = "EU"
max-player-count = 10
listen-address = "0.0.0.0"
listen-port = 15780

[game]
max-level = 110
logout-duration = 2
desired-ticks = 128
client-timeout = 30
deletion-time = 10080
max-follow-distance = 300.0

[game.spawner]
radius = 500
amount = 10

[game.spawner.unique.tiger-woman]
min = 60
max = 300

[game.spawner.unique.uruchi]
min = 60
max = 300

[game.spawner.unique.isyutaru]
min = 60
max = 300

[game.spawner.unique.bonelord]
min = 60
max = 300

[game.masteries]
european-per-level = 2
chinese-per-level = 2

[database]
host = "localhost"
user = "skrillax"
password = "skrillax"
database = "skrillax"